service: backend
app: temperature-bot
org: berabulut


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN_KEY: ${env:TWITTER_ACCESS_TOKEN_KEY}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    GMAIL_USER: ${env:GMAIL_USER}
    GMAIL_PASS: ${env:GMAIL_PASS}
    DATABASE_URL: ${env:DATABASE_URL}
    SLS_DEBUG: ${env:SLS_DEBUG}

functions:
  mail:
    handler: handlers/mailhandler.mail
    timeout: 30
    description: Mail fetched temperature.
    events:
      - http: 
          path: mail
          method: get
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "arn:aws:lambda:us-east-1:211144193599:function:backend-dev-mail"


  tweet:
    handler: handlers/tweethandler.tweet
    timeout: 30
    description: Mail fetched temperature.
    events:
      - http: 
          path: tweet
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function